title: Blog SPE
author: Semillero de Política Económica
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    bibtex_bibfiles:
      - referencias.bib

repository:
  url: https://github.com/sempolecon/spe-blog                          
  branch: main                                   

html:
  use_issues_button: true
  use_repository_button: true
  baseurl: "/spe-blog"